const games = {
	"2048": "2048.html",
	"Big Tower Tiny Square": "btts.html",
	"Drive Mad": "drivemad.html",
	"Gun Spin": "gunspin.html",
	"Poly Track": "polytrack.html",
	"Plants vs Zombies": "pvz.html",
	"Retro Bowl": "retrobowl.html",
	"Tanuki Sunset": "tanukisunset.html",
	"1v1 Lol": "1v1lol.html",
	"8 Ball": "8ball.html",
	"1": "1.html",
	"Basketball Random": "basketballrandom.html",
	"Ages of Conflict": "agesofconflict.html",
	"Bitlife": "bitlife.html",
	"9007199254740992": "9007199254740992.html",
	"Bad Icecream": "badicecream.html",
	"Bad Icecream 2": "badicecream2.html",
	"Bad Icecream 3": "badicecream3.html",
	"Bob the Robber 2": "bobtherobber2.html",
	"Big Tower Tiny Square": "btts.html",
	"A Dance of Fire and Ice" : "adofai",
	"60 Second Burger Run" : "60sbr",
	"Bob the Robber": "bobtherobber.html",
	"Bob the Robber 5": "bobtherobber5.html",
	"Bloons Tower Defense 2": "btd2.html",
	"Bloons Tower Defense 3": "btd3.html",
	"Bloons Tower Defense 4": "btd4.html",
	"Bloxorz": "bloxorz.html",
	"Burrito Bison": "burritobison.html",
	"Burrito Bison Launcha Libre": "burritobisonlaunchalibre.html",
	"Burrito Bison Revenge": "burritobisonrevenge.html",
	"Basketball Legends": "basketballlegends.html",
	"Funny Shooter 2": "funnyshooter2.html",
	"Fire Boy and Water Girl": "fireboyandwatergirl.html",
	"Fire Boy and Water Girl 2": "fireboyandwatergirl2.html",
	"Fire Boy and Water Girl 3": "fireboyandwatergirl3.html",
	"Duck Life": "ducklife.html",
	"Duck Life 2": "ducklife2.html",
	"Duck Life 3": "ducklife3.html",
	"Duck Life 4": "ducklife4.html",
	"Duck Life 5": "ducklife5.html",
	"Drift Boss": "driftboss.html",
	"Stickmin Breaking Bank": "stickminbreakingbank.html",
	"Stickmin Escaping Prison": "stickminescapingprison.html",
	"Stickmin Fleeing the Complex": "stickminfleeingthecomplex.html",
	"Stickmin Infiltrating the Airship": "stickmininfiltratingtheairship.html",
	"Idle Breakout": "idlebreakout.html",
	"Idle Miner Tycoon": "idleminertycoon.html",
	"Learn to Fly": "learntofly.html",
	"Learn to Fly 2": "learntofly2.html",
	"Learn to Fly 3": "learntofly3.html",
	"Learn to Fly Idle": "learntoflyidle.html",
	"OVO": "ovo.html",
	"OVO 2": "ovo2.html",
	"Papa's Bakeria": "papasbakeria.html",
	"Papa's Burgeria": "papasburgeria.html",
	"Papa's Cheeseria": "papascheeseria.html",
	"Papa's Cupcakeria": "papascupcakeria.html",
	"Papa's Donuteria": "papasdonuteria.html",
	"Papa's Freezeria": "papasfreezeria.html",
	"Papa's Hotdoggeria": "papashotdoggeria.html",
	"Papa's Pancakeria": "papaspancakeria.html",
	"Papa's Pizzeria": "papaspizzeria.html",
	"Papa's Scooperia": "papasscooperia.html",
	"Papa's Taco Mia!": "papastacomia.html",
	"Papa's Wingeria": "papaswingeria.html",
	"Papa's Sushiria": "papassushiria.html",
	"Papa's Pastaria": "papaspastaria.html",
	"Pixel Speedrun": "pixelspeedrun.html",
	"Pixel Shooter": "pixelshooter.html",
	"Pizza Tower": "pizzatower.html",
	"Red Ball": "redball.html",
	"Red Ball 2": "redball2.html",
	"Red Ball 3": "redball3.html",
	"Red Ball 4": "redball4.html",
	"Red Ball 4 vol 2": "redball4vol2.html",
	"Red Ball 4 vol 3": "redball4vol3.html",
	"Riddle School": "riddleschool.html",
	"Riddle School 2": "riddleschool2.html",
	"Riddle School 3": "riddleschool3.html",
	"Riddle School 4": "riddleschool4.html",
	"Riddle School 5": "riddleschool5.html",
	"Riddle School Transfer": "riddletransfer.html",
	"Riddle School Transfer 2": "riddletransfer2.html",
	"Run": "run.html",
	"Run 2": "run.html2",
	"Run 3": "run.html3",
	"Rooftop Snipers": "rooftopsnipers.html",
	"Boxing Random": "boxingrandom.html",
	"Celeste": "celeste.html",
	"Celeste 2": "celeste2.html",
	"Cookie Clicker": "cookieclicker.html",
	"Baldis Basics": "baldisbasics.html",
	"Balls and Bricks": "ballsandbricks.html",
	"Basketball Stars": "basketballstars.html",
	"Raft Wars": "raftwars.html",
	"Super Mario 64": "supermario64.html",
	"Throw a Potato": "throwapotato.html",
	"Throw a Potato Again": "throwapotatoagain.html",
	"Time Shooter 2": "timeshooter2.html",
	"Test": "testingGames.html"
};
export default games;
